version: "3.9"

services:
  backend:
    build: ./backend
    container_name: algomentor-backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: algomentor-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
